#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run a script on the host or in the web container.
## Usage: devkit-run-script [script] [flags] [args]
## Example: "ddev devkit-run-script scripts/example.sh --web"
## Flags: [{"Name":"host","Usage":"Run the script on the host"},{"Name":"web","Usage":"Run the script in the web container"}]
## Aliases: devkit:run-script

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Defaults
SCRIPT=""
WHERE=host
ARGS=()

# Get script path
if [[ -z "$SCRIPT" ]]; then
  SCRIPT="$1"; shift
else
  ARGS+=("$1"); shift
fi

# Parse flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    --web)  WHERE=web;  shift; continue ;;
    --host) WHERE=host; shift; continue ;;
    --)     shift; ARGS+=("$@"); break ;;
  esac
done

# Validate
if [[ -z "${SCRIPT-}" ]]; then
  echo "[script] is required."
  exit 2
fi

if [[ "$WHERE" == host ]]; then
  SCRIPT_PATH="$DDEV_APPROOT/$SCRIPT"
else
  SCRIPT_PATH="$SCRIPT"
fi

# Summarise
echo "Running script '$SCRIPT' in '$WHERE'..."

# Commands
if [[ "$WHERE" == host ]]; then
  exec bash "$SCRIPT_PATH" "${ARGS[@]}"
else
  exec ddev exec bash "$SCRIPT_PATH" "${ARGS[@]}"
fi
