#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Frontend testing tasks.
## Usage: site-test-frontend
## Example: "ddev site-test-frontend"
## Aliases: site:test:frontend,site-test-fe,site:test:fe,site-frontend-test,site:frontend:test,site-fe-test,site:fe:test

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-test-frontend.sh" --where=host
