#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run backend refresh tasks.
## Usage: site-refresh-backend
## Example: "ddev site-refresh-backend"
## Aliases: site:refresh:backend,site-be-refresh,site:be:refresh

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-refresh-backend.sh" --where=host
