#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run frontend update tasks.
## Usage: site-update-frontend
## Example: "ddev site-update-frontend"
## Aliases: site:update:frontend,site-fe-update,site:fe:update

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-update-frontend.sh" --where=host
