#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Installation tasks.
## Usage: site-install
## Example: "ddev site-install"
## Aliases: site:install,site-installation,site:installation

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-install.sh" --where=host
