#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Backend testing tasks.
## Usage: site-test-backend
## Example: "ddev site-test-backend"
## Aliases: site:test:backend,site-test-be,site:test:be,site-backend-test,site:backend:test,site-be-test,site:be:test

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-script-run --script="$SITE_SCRIPTS/site-test-backend.sh" --location=host
