#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run backend synchronisation tasks.
## Usage: site-sync-backend
## Example: "ddev site-sync-backend"
## Aliases: site:sync:backend,site-be-sync,site:be:sync

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-sync-backend.sh" --where=host
