#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Enable development mode.
## Usage: site-mode-development
## Example: "ddev site-mode-development"
## Aliases: site:mode:development,site-mode-dev,site:mode:dev,site-development-mode,site:development:mode,site-dev-mode,site:dev:mode

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-mode-development.sh" --where=host
