#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run frontend refresh tasks.
## Usage: site-refresh-frontend
## Example: "ddev site-refresh-frontend"
## Aliases: site:refresh:frontend,site-fe-refresh,site:fe:refresh

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-refresh-frontend.sh" --where=host
