#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Backend build tasks.
## Usage: site-build-backend
## Example: "ddev site-build-backend"
## Aliases: site:build:backend,site-build-be,site:build:be,site-backend-build,site:backend:build,site-be-build,site:be:build

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-build-backend.sh" --where=host
