#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run frontend test tasks.
## Usage: site-test-frontend [flags] [args]
## Example: "ddev site-test-frontend"
## Aliases: site:test:frontend,site-fe-test,site:fe:test

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script "$SITE_SCRIPTS/site-test-frontend.sh" "${@}" --host
