#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Backend synchronisation tasks.
## Usage: site-sync-backend
## Example: "ddev site-sync-backend"
## Aliases: site:sync:backend,site-sync-be,site:sync:be,site-backend-sync,site:backend:sync,site-be-sync,site:be:sync

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-script-run --script="$SITE_SCRIPTS/site-sync-backend.sh" --where=host
