#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run initialisation tasks.
## Usage: site-initialisation [flags] [args]
## Example: "ddev site-initialisation"
## Aliases: site:initialisation,site-init,site:init

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

echo "'site-initialisation' logic will be added here."
