#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run backend build tasks.
## Usage: site-build-backend [flags] [args]
## Example: "ddev site-build-backend"
## Aliases: site:build:backend,site-be-build,site:be:build

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

echo "'site-build-backend' logic will be added here."
