#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run backend update tasks.
## Usage: site-update-backend [flags] [args]
## Example: "ddev site-update-backend"
## Aliases: site:update:backend,site-be-update,site:be:update

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-update-backend.sh" "${@}" --host
