#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run backend test tasks.
## Usage: site-test-backend [flags] [args]
## Example: "ddev site-test-backend"
## Aliases: site:test:backend,site-be-test,site:be:test

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-test-backend.sh" "${@}" --where=host
