#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Enable production mode.
## Usage: site-mode-production
## Example: ddev site-mode-production
## Aliases: site:mode:production,site-mode-prod,site:mode:prod,site-production-mode,site:production:mode,site-prod-mode,site:prod:mode

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Run the script
ddev devkit-script-run --script=".ddev/site-devkit/site/scripts/site-mode-production.sh" --location=host
