#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Authentication tasks.
## Usage: site-auth
## Example: "ddev site-auth"
## Aliases: site:auth,site-authentication,site:authentication

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-script-run --script="$SITE_SCRIPTS/site-auth.sh" --where=host
