#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Installation tasks.
## Usage: site-install
## Example: "ddev site-install"
## Aliases: site:install,site-installation,site:installation

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Run the script
ddev devkit-script-run --script=".ddev/site-devkit/site/scripts/site-install.sh" --location=host
