#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Synchronisation tasks.
## Usage: site-sync
## Example: "ddev site-sync"
## Aliases: site:sync

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-script-run --script="$SITE_SCRIPTS/site-sync.sh" --location=host
