#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run initialisation tasks.
## Usage: site-initialisation
## Example: "ddev site-initialisation"
## Aliases: site:initialisation,site-init,site:init

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-initialisation.sh" --where=host
