#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Run backend build tasks.
## Usage: site-build-backend [flags] [args]
## Example: "ddev site-build-backend"
## Aliases: site:build:backend,site-be-build,site:be:build

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the site script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-build-backend.sh" "${@}" --where=host
