#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Enable production mode.
## Usage: site-mode-production
## Example: "ddev site-mode-production"
## Aliases: site:mode:production,site-mode-prod,site:mode:prod,site-production-mode,site:production:mode,site-prod-mode,site:prod:mode

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-run-script --script="$SITE_SCRIPTS/site-mode-production.sh" --where=host
