#!/usr/bin/env bash

#ddev-generated
## Command provided by https://github.com/colinstillwell/ddev-site-devkit
## Description: Frontend synchronisation tasks.
## Usage: site-sync-frontend
## Example: "ddev site-sync-frontend"
## Aliases: site:sync:frontend,site-sync-fe,site:sync:fe,site-frontend-sync,site:frontend:sync,site-fe-sync,site:fe:sync

# Exit on error; treat unset variables as errors; fail pipelines if any command fails
set -euo pipefail

# Path to the site scripts
SITE_SCRIPTS=".ddev/site-devkit/site/scripts"

# Run the script
ddev devkit-script-run --script="$SITE_SCRIPTS/site-sync-frontend.sh" --where=host
